"""Create article analyses table

Revision ID: 72cec6b470a6
Revises: bc7fb13e2ea0
Create Date: 2026-09-30 11:11:53.079051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cec6b470a6'
down_revision: Union[str, Sequence[str], None] = 'bc7fb13e2ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_analyses_article_id'), 'article_analyses', ['article_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_analyses_article_id'), table_name='article_analyses')
    op.drop_table('article_analyses')
    # ### end Alembic commands ###
